# Generated by Django 2.0.9 on 2018-11-28 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('reply_comment_id', models.PositiveIntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed_target', models.PositiveIntegerField(default=0)),
                ('total_target', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='horizon_target_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('critical_flag', models.BooleanField(default=False)),
                ('countable_flag', models.BooleanField(default=False)),
                ('completed_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('remind_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=300, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('user_role_id', models.PositiveIntegerField(default=0)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
                ('folder', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend_service.folder')),
            ],
        ),
        migrations.CreateModel(
            name='sub_target_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('completed_flag', models.BooleanField(default=False)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
                ('target', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend_service.horizon_target_individual')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sub_target',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend_service.sub_target_individual'),
        ),
        migrations.AddField(
            model_name='event',
            name='target',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend_service.horizon_target_individual'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend_service.horizon_target_individual'),
        ),
    ]
