# Generated by Django 2.0.9 on 2018-10-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='horizon_target_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.EmailField(max_length=254)),
                ('critical_flag', models.CharField(max_length=300)),
                ('countable_flag', models.DateTimeField(auto_now_add=True)),
                ('completed_flag', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
