# Generated by Django 2.0.9 on 2018-11-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_by_id',
            field=models.EmailField(max_length=254),
        ),
    ]
