# Generated by Django 2.0.9 on 2018-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon_target_group',
            name='countable_flag',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='horizon_target_group',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='horizon_target_group',
            name='expire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horizon_target_group',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
