# Generated by Django 2.0.9 on 2018-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0002_auto_20181019_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='horizon_target_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('critical_flag', models.CharField(max_length=300)),
                ('countable_flag', models.CharField(max_length=300)),
                ('completed_flag', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('remind_date', models.DateTimeField()),
                ('status', models.CharField(max_length=300)),
                ('target_group_id', models.PositiveIntegerField()),
                ('user_role_id', models.PositiveIntegerField()),
                ('created_by_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='horizon_target_group',
            name='created_by_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
