# Generated by Django 2.0.9 on 2018-11-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0002_auto_20181129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_by_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='created_by_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sub_target_individual',
            name='created_by_id',
            field=models.EmailField(max_length=254),
        ),
    ]
