# Generated by Django 2.0.9 on 2018-11-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0003_auto_20181129_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon_target_individual',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_by_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='created_by_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_target_individual',
            name='created_by_id',
            field=models.CharField(max_length=100),
        ),
    ]
