# Generated by Django 2.0.9 on 2018-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0004_auto_20181024_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='completed_flag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='countable_flag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='critical_flag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
