# Generated by Django 2.0.9 on 2018-12-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0004_auto_20181129_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon_target_individual',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
