# Generated by Django 2.0.9 on 2018-10-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0005_auto_20181024_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizon_target_individual',
            name='status',
        ),
    ]
