# Generated by Django 2.0.9 on 2019-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0005_horizon_target_individual_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mention_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
