# Generated by Django 2.0.9 on 2018-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0006_remove_horizon_target_individual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon_target_individual',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
