# Generated by Django 2.0.9 on 2019-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0007_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
