# Generated by Django 2.0.9 on 2018-10-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0007_horizon_target_individual_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='completed_flag',
            field=models.BooleanField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='countable_flag',
            field=models.BooleanField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='critical_flag',
            field=models.BooleanField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='remind_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=300, null=True),
        ),
    ]
