# Generated by Django 2.0.9 on 2018-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0008_auto_20181030_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='created_by_id',
            field=models.PositiveIntegerField(default=123456),
        ),
    ]
