# Generated by Django 2.0.9 on 2018-11-02 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0009_auto_20181030_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='horizon_target_group',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='horizon_target_individual',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
