# Generated by Django 2.0.9 on 2018-11-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0010_auto_20181102_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon_target_group',
            name='folder_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horizon_target_individual',
            name='folder_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_by_id',
            field=models.PositiveIntegerField(default=123456),
        ),
    ]
