# Generated by Django 2.0.9 on 2018-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0011_auto_20181105_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_target_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('completed_flag', models.BooleanField(default=False)),
                ('target_id_individual', models.PositiveIntegerField(default=0)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
    ]
