# Generated by Django 2.0.9 on 2018-11-06 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0012_sub_target_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('target_id_individual', models.PositiveIntegerField(default=0)),
                ('reply_comment_id', models.PositiveIntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
        migrations.AlterField(
            model_name='sub_target_individual',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
