# Generated by Django 2.0.9 on 2018-11-08 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0013_auto_20181106_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_target_id', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.PositiveIntegerField(default=123456)),
            ],
        ),
        migrations.AddField(
            model_name='sub_target_individual',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
