# Generated by Django 2.0.9 on 2018-11-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0014_auto_20181108_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizon_target_individual',
            name='countable_flag',
        ),
    ]
