# Generated by Django 2.0.9 on 2018-11-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0015_remove_horizon_target_individual_countable_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon_target_individual',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
