# Generated by Django 2.0.9 on 2018-11-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0016_horizon_target_individual_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='total_target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
