# Generated by Django 2.0.9 on 2018-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0018_auto_20181114_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon_target_individual',
            name='critical_flag',
            field=models.BooleanField(default=False),
        ),
    ]
