# Generated by Django 2.0.9 on 2018-11-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='InStastics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department_desc',
        ),
    ]
