# Generated by Django 2.0.9 on 2018-11-29 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181128_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_to',
            field=models.ManyToManyField(blank=True, related_name='_user_report_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
