# Generated by Django 2.0.9 on 2019-01-11 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181129_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action_access_permission',
            field=models.ManyToManyField(blank=True, related_name='asdfdsafsda', to=settings.AUTH_USER_MODEL),
        ),
    ]
