# Generated by Django 2.0.9 on 2019-01-11 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_action_access_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='action_access_permission',
            field=models.ManyToManyField(blank=True, related_name='action_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
