# Generated by Django 2.0.9 on 2019-01-15 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190111_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='action_access_permission',
        ),
        migrations.AddField(
            model_name='user',
            name='give_my_action_to',
            field=models.ManyToManyField(blank=True, related_name='own_action_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='report_to',
            field=models.ManyToManyField(blank=True, related_name='report_to_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
